version: "3"

services:
  vote:
    build: ./vote
    ports:
      - "5000:80"
    networks:
      - frontend
    depends_on:
      - redis

  result:
    build: ./result
    ports:
      - "5001:80"
    networks:
      - backend
    depends_on:
      - db

  worker:
    build: ./worker
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    networks:
      - frontend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  frontend:
  backend:

volumes:
  db-data:
