name: Deploy to EC2

on:
  push:
    branches:
      - main  # Bisa ditambah 'master' kalau mau trigger dari dua branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@54.224.137.106 << 'EOF'
          cd /home/ec2-user/app || exit 1
          git pull origin main || exit 1
          docker compose down || true
          docker compose up -d --build || exit 1
        EOF
